<a href="https://colab.research.google.com/github/mdtanjimhasanashik/DeepGene-TB/blob/main/gene_expression_preprocessing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

# Load gene expression dataset
df = pd.read_csv("/content/drive/MyDrive/Data_Set/RawData_MetaData.csv")  # Update path as needed
print("Column names:", df.columns.tolist())
print("Dataset shape:", df.shape)

# Identify sample and label columns
sample_col = df.columns[0]
label_col = df.columns[-1]

# Extract expression data and labels
gene_expression = df.iloc[:, 1:-1]  # All genes (exclude sample and label)
labels = df[label_col]

# Split into condition groups
group1 = gene_expression[labels == labels.unique()[0]]
group2 = gene_expression[labels == labels.unique()[1]]

# --- Statistical Significance: p-value ---
p_values = [ttest_ind(group1[col], group2[col], equal_var=False).pvalue for col in gene_expression.columns]
pval_df = pd.DataFrame({"Gene": gene_expression.columns, "p_value": p_values})

# --- Biological Significance: log2 fold change ---
group1_mean = group1.mean()
group2_mean = group2.mean()
fold_change = group1_mean / group2_mean.replace(0, np.nan)
log2fc = np.log2(fold_change.replace(0, np.nan))
fc_df = pd.DataFrame({"Gene": gene_expression.columns, "log2fc": log2fc})

# --- Merge both results ---
deg_df = pd.merge(pval_df, fc_df, on="Gene")

# --- Combined Significance ---
deg_df["Combined_Significant"] = (deg_df["p_value"] < 0.05) & (deg_df["log2fc"].abs() > 1)

# --- Filter only combined significant DEGs ---
combined_sig_genes = deg_df[deg_df["Combined_Significant"]].copy()

# --- Upregulated (log2fc > 1) = 1, Downregulated (log2fc < -1) = 0 ---
combined_sig_genes["Target"] = np.where(combined_sig_genes["log2fc"] > 1, 1, 0)

# --- Print up/down counts ---
up_count = (combined_sig_genes["Target"] == 1).sum()
down_count = (combined_sig_genes["Target"] == 0).sum()

print("\n=== DEG CLASSIFICATION ===")
print(f"Upregulated DEGs (Target=1): {up_count}")
print(f"Downregulated DEGs (Target=0): {down_count}")

# --- Final dataframe with gene names, log2fc, p_value, target ---
final_deg_df = combined_sig_genes[["Gene", "log2fc", "p_value", "Target"]]
print("\nSample of final DEGs dataframe:")
print(final_deg_df.head())

# --- Save to CSV ---
final_deg_df.to_csv("DEGs_Combined_UpDown_With_Target.csv", index=False)

# Optional: if you want a gene expression matrix with target info:
selected_genes = final_deg_df["Gene"].tolist()
expr_only = df[selected_genes]
expr_with_target = expr_only.T.copy()
expr_with_target["log2fc"] = combined_sig_genes.set_index("Gene")["log2fc"]
expr_with_target["p_value"] = combined_sig_genes.set_index("Gene")["p_value"]
expr_with_target["Target"] = combined_sig_genes.set_index("Gene")["Target"]
expr_with_target.to_csv("DEGs_Expression_Log2FC_pvalue_Target.csv")

Column names: ['Sample_Names', 'TSPAN6', 'TNMD', 'DPM1', 'SCYL3', 'C1orf112', 'FGR', 'CFH', 'FUCA2', 'GCLC', 'NFYA', 'STPG1', 'NIPAL3', 'LAS1L', 'ENPP4', 'SEMA3F', 'CFTR', 'ANKIB1', 'CYP51A1', 'KRIT1', 'RAD52', 'BAD', 'LAP3', 'CD99', 'HS3ST1', 'AOC1', 'WNT16', 'HECW1', 'MAD1L1', 'LASP1', 'SNX11', 'TMEM176A', 'M6PR', 'KLHL13', 'CYP26B1', 'ICA1', 'DBNDD1', 'ALS2', 'CASP10', 'CFLAR', 'TFPI', 'NDUFAF7', 'RBM5', 'MTMR7', 'SLC7A2', 'ARF5', 'SARM1', 'POLDIP2', 'PLXND1', 'AK2', 'CD38', 'FKBP4', 'KDM1A', 'RBM6', 'CAMKK1', 'RECQL', 'VPS50', 'HSPB6', 'ARHGAP33', 'NDUFAB1', 'PDK4', 'SLC22A16', 'ZMYND10', 'ABCB5', 'ARX', 'SLC25A13', 'ST7', 'CDC27', 'SLC4A1', 'CALCR', 'HCCS', 'DVL2', 'PRSS22', 'UPF1', 'SKAP2', 'SLC25A5', 'MCUB', 'HOXA11', 'POLR2J', 'DHX33', 'MEOX1', 'THSD7A', 'LIG3', 'RPAP3', 'ACSM3', 'LOC81691', 'CIAPIN1', 'SPPL2B', 'FAM214B', 'COPZ2', 'PRKAR2B', 'MSL3', 'CREBBP', 'TSPOAP1', 'MPO', 'PON1', 'GCFC2', 'WDR54', 'CROT', 'ABCB4', 'KMT2E', 'RHBDD2', 'SOX8', 'IBTK', 'ZNF195', 'MYCBP2', 'FBXL3', 'ITGAL', 'PDK2', 'ITGA3', 'ZFX', 'LAMP2', 'ITGA2B', 'ASB4', 'GDE1', 'C19orf60', 'CRLF1', 'OSBPL7', 'TMEM98', 'YBX2', 'KRT33A', 'MAP3K14', 'ABCC8', 'CACNG3', 'TMEM132A', 'AP2B1', 'TAC1', 'ZNF263', 'CX3CL1', 'SPATA20', 'CACNA1G', 'TNFRSF12A', 'DLX6', 'MAP3K9', 'RALA', 'BAIAP2L1', 'KDM7A', 'ETV1', 'AGK', 'ALDH3B1', 'TTC22', 'PHTF2', 'CCL26', 'FARP2', 'USH1C', 'GGCT', 'DBF4', 'TBXA2R', 'IFRD1', 'LGALS14', 'COX10', 'GTF2IRD1', 'PAF1', 'VPS41', 'ARHGAP44', 'ELAC2', 'SCIN', 'ARSD', 'PNPLA4', 'MYH13', 'ADIPOR2', 'CDKL3', 'UPP2', 'PRSS21', 'MARK4', 'PROM1', 'CCDC124', 'CEACAM21', 'PAFAH1B1', 'NOS2', 'DNAH9', 'KIAA0100', 'SLC13A2', 'GAS7', 'TRAPPC6A', 'MATK', 'CEACAM7', 'CD79B', 'SCN4A', 'ST7L', 'TKTL1', 'PAX6', 'RPUSD1', 'RHBDF1', 'LUC7L', 'CACNA2D2', 'BAIAP3', 'TSR3', 'PIGQ', 'CRAMP1', 'TEAD3', 'SELE', 'DNAJC11', 'FMO3', 'MYLIP', 'NOX1', 'E2F2', 'PSMB1', 'SYN1', 'JARID2', 'CDKL5', 'CAMK1G', 'CDK11A', 'NADK', 'TFAP2B', 'TFAP2D', 'DLEC1', 'CYTH3', 'ADAM22', 'SYPL1', 'CYB561', 'SPAG9', 'CELSR3', 'AASS', 'PLEKHG6', 'SS18L2', 'MPND', 'MGST1', 'CRY1', 'PGLYRP1', 'NFIX', 'ST3GAL1', 'MMP25', 'IL32', 'PKD1', 'MAPK8IP2', 'MED24', 'RHOBTB2', 'HEATR5B', 'SEC62', 'RPS20', 'CSDE1', 'UBE3C', 'REV3L', 'TENM1', 'PAX7', 'MASP2', 'IYD', 'FAM76A', 'TRAF3IP3', 'POMT2', 'VTA1', 'MLXIPL', 'BAZ1B', 'RANBP9', 'ETV7', 'SPRTN', 'METTL13', 'DYRK4', 'ZNF207', 'UQCRC1', 'STARD3NL', 'CD9', 'HHATL', 'NCAPD2', 'IFFO1', 'GIPR', 'PHF7', 'SEMA3G', 'NISCH', 'STAB1', 'FUZ', 'SLC6A13', 'IDS', 'PRSS3', 'ZNF200', 'CD4', 'LRRC23', 'BTK', 'HFE', 'SCMH1', 'FYN', 'HIVEP2', 'FMO1', 'ELOA', 'LYPLA2', 'CLCN6', 'MRC2', 'NME1-NME2', 'SLC6A7', 'TSPAN9', 'BTBD7', 'APBA3', 'MKS1', 'ABHD5', 'ANOS1', 'AKAP8L', 'MBTD1', 'UTP18', 'RNF216', 'TTC19', 'PTBP1', 'DPF1', 'SYT7', 'LARS2', 'PIK3C2A', 'PLAUR', 'ANLN', 'WIZ', 'GPR21', 'DCN', 'QPCTL', 'PPP5C', 'CEP68', 'MAP4K3', 'ZBTB32', 'TYROBP', 'TMEM159', 'GABRA3', 'BRCA1', 'ERCC1', 'CD22', 'SEMA3B', 'MBTPS2', 'PRICKLE3', 'LTF', 'EXTL3', 'NR1H4', 'ELOVL5', 'ALOX5', 'KDM5D', 'CALCOCO1', 'UBR7', 'MAP4K5', 'EHD3', 'PSMC4', 'MAN2B2', 'SLC7A14', 'CLDN11', 'SLC25A39', 'MVP', 'NUB1', 'PGM3', 'RWDD2A', 'CLK1', 'POLR3B', 'ANGEL1', 'RNF14', 'DNASE1L1', 'DDX11', 'HEBP1', 'GPRC5A', 'MAMLD1', 'CD6', 'TACC3', 'UFL1', 'POLA2', 'ZC3H3', 'CAPN1', 'ACPP', 'MDH1', 'SLC30A9', 'MTMR11', 'COX15', 'CCDC88C', 'YAF2', 'ZMYND11', 'WAS', 'DPEP1', 'BID', 'MATR3', 'NPC1L1', 'XYLT2', 'RGPD5', 'STMN4', 'NUDCD3', 'ISL1', 'CHDH', 'IL20RA', 'CLCA1', 'CLCA4', 'GLT8D1', 'ATP2C1', 'IGF1', 'SLC38A5', 'RALBP1', 'RUFY3', 'CNTN1', 'SLC11A1', 'WWTR1', 'AGPS', 'CXorf56', 'ATP1A2', 'TTC27', 'ZNF582', 'VSIG2', 'PHLDB1', 'MARCO', 'CYP24A1', 'PRDM11', 'SYT13', 'SNAI2', 'CD74', 'HGF', 'ZRANB1', 'NCDN', 'ADGRA2', 'ZFP64', 'MNAT1', 'SAMD4A', 'RUNX3', 'MRE11', 'PLEKHB1', 'SERPINB1', 'CYP3A43', 'SLC7A9', 'SPAST', 'NRXN3', 'OSBPL5', 'AQR', 'CPS1', 'C8B', 'FHL1', 'RTFDC1', 'GABRA1', 'NLRP2', 'SLC45A4', 'RNF10', 'ZNF839', 'ZDHHC6', 'GRAMD1B', 'RNH1', 'NDUFS1', 'RB1CC1', 'ERP44', 'ALAS1', 'BIRC3', 'AKAP11', 'GLRX2', 'SNAPC1', 'DERA', 'STRAP', 'ABCC2', 'DEF6', 'PLEKHO1', 'GCLM', 'UBR2', 'EHD2', 'DEPDC1', 'CCDC28A', 'RRAGD', 'HSF2', 'PHF20', 'HSD17B6', 'NR1H3', 'TYMP', 'NCAPH2', 'TOMM34', 'SEC63', 'KPNA6', 'VIM', 'RTEL1', 'FAS', 'RNASET2', 'CD44', 'KCNG1', 'AGPAT4', 'SLAMF7', 'BTN3A1', 'MIPEP', 'PRKCH', 'INSRR', 'IFNGR1', 'B4GALT7', 'SH2D2A', 'VRK2', 'TNFRSF1B', 'VEZT', 'POU2F2', 'BRD9', 'SNX1', 'TBPL1', 'ARNTL2', 'BCLAF1', 'SLC39A9', 'ANK1', 'IBSP', 'TFB1M', 'RABEP1', 'HMGB3', 'NUP160', 'BAK1', 'MUSK', 'IKZF2', 'GRN', 'FAM13B', 'ARHGAP31', 'CENPQ', 'SARS', 'RANBP3', 'ARID4A', 'TSSC1', 'PNPLA6', 'IFT88', 'ALG1', 'ZCCHC8', 'ABCF2', 'CHPF2', 'LRRC7', 'FUT8', 'UBA6', 'GAB2', 'ATP6V0A1', 'PIAS1', 'SLC4A7', 'APBA2', 'MAP2K3', 'EFCAB1', 'TMSB10', 'ASTE1', 'RNF19A', 'PEX3', 'GABARAPL2', 'MYOC', 'SH3YL1', 'FAM136A', 'VCL', 'DEPDC1B', 'DAPK2', 'NSMAF', 'ADSS', 'STAP1', 'TIMP2', 'RFC1', 'TBC1D23', 'CUL3', 'MYOM2', 'OTC', 'CYP46A1', 'ZZZ3', 'SLC18A1', 'USP2', 'CASR', 'TUBG2', 'RPL26L1', 'FLT4', 'NSUN2', 'FBXO42', 'MFAP3', 'MRI1', 'METTL1', 'HOXC8', 'AGA', 'PI4K2B', 'BOD1L1', 'MAT2B', 'TLL1', 'EDC4', 'TRIO', 'VCAN', 'CLEC16A', 'MSR1', 'CDH1', 'SKIV2L2', 'DNAH5', 'ZFYVE16', 'RIPOR1', 'C6', 'RAI14', 'SOX30', 'PNKP', 'BEST2', 'PHLPP2', 'SPDL1', 'STAU2', 'PQLC2', 'CTNS', 'RTN4R', 'PHF23', 'CDH10', 'INPP4A', 'RAB27B', 'PSMA4', 'MYO16', 'LSG1', 'PARP3', 'TNC', 'THAP3', 'RIPOR3', 'TDP1', 'AIFM2', 'C2orf83', 'SPATA7', 'MED17', 'RETSAT', 'CAPG', 'AP2S1', 'USH2A', 'ZPBP', 'TG', 'ADAM28', 'BARX2', 'DCUN1D1', 'JADE2', 'ZIC2', 'LCP2', 'TRIT1', 'ADRB1', 'GUCA2B', 'CUL7', 'CTNNA1', 'PHKA2', 'CNTLN', 'EPHA3', 'HSPA5', 'DSG2', 'GEMIN8', 'OFD1', 'GPM6B', 'MAGEC2', 'PREX2', 'WDR37', 'YTHDC2', 'CTPS2', 'ATP6V1H', 'POLR2B', 'FAM214A', 'ARAP2', 'TPR', 'CP', 'KIAA0556', 'DTNBP1', 'XK', 'ANO2', 'C12orf4', 'SCML1', 'WWC3', 'ARHGAP6', 'FAM184B', 'MAP4', 'GOPC', 'ROS1', 'USP28', 'HDAC9', 'TSPAN17', 'NOP16', 'CC2D2A', 'RRM2B', 'ZNF800', 'TNFRSF17', 'SNX29', 'LMO3', 'MRPS10', 'GUCA1A', 'RSF1', 'VPS13D', 'CELF2', 'FAM120A', 'R3HDM1', 'COL9A2', 'KITLG', 'ERCC8', 'ADAMTS6', 'H6PD', 'VAMP3', 'PER3', 'UTS2', 'TNFRSF9', 'EPN3', 'LTBP1', 'RCN1', 'ELN', 'RFC2', 'ARID1B', 'CLPTM1L', 'NEDD4L', 'FOXP3', 'PPP1R3F', 'HEXB', 'PTCD2', 'KIAA2022', 'JKAMP', 'DKK3', 'ARHGEF5', 'NFE2L3', 'MCUR1', 'LIMA1', 'LETMD1', 'SLC4A8', 'LAMC3', 'PTGER3', 'TNIP3', 'MAPK9', 'COL23A1', 'BCAR1', 'FAM160A2', 'HERPUD1', 'HOMER3', 'RAD51', 'POLQ', 'PIK3CB', 'CYBA', 'THOC3', 'HEBP2', 'MPHOSPH9', 'PLEKHA5', 'PRSS8', 'SIKE1', 'RRP12', 'FNIP2', 'MSMO1', 'TTC17', 'ALX4', 'FSTL4', 'FOXN3', 'METTL24', 'AKR7A2', 'MRTO4', 'NNAT', 'USE1', 'MCF2L2', 'NRIP2', 'LAMA3', 'AP5M1', 'ANAPC4', 'KCNQ1', 'TRAPPC3', 'THRAP3', 'PHPT1', 'ENTPD2', 'LY75', 'ARID4B', 'OPN3', 'SDCCAG8', 'PTPRN', 'HHAT', 'KIF1B', 'FOXC1', 'TBC1D22A', 'SYNE2', 'PLEKHH1', 'ATP9A', 'SPO11', 'CBLN4', 'CHRDL2', 'FAM168A', 'RELT', 'GALC', 'NOP58', 'SZRD1', 'KCNH2', 'CUL1', 'FAM114A2', 'CYFIP2', 'TAB2', 'GINM1', 'EIF2AK2', 'USP36', 'KMT2C', 'MCOLN3', 'CCDC85A', 'PUM2', 'MRPL43', 'ITIH4', 'ITIH1', 'HPF1', 'ZFR', 'ZNF280C', 'NPFFR2', 'PHF21B', 'TRAF1', 'RC3H2', 'KIFC1', 'IL17RB', 'TRAF3IP2', 'GYG2', 'DCBLD2', 'SERPINB3', 'SOAT1', 'PKP2', 'MSH4', 'F7', 'GDI2', 'PRDM1', 'ATG5', 'TMCC3', 'PITHD1', 'MTA3', 'USP13', 'ATP11B', 'LAMC2', 'CDK14', 'SEC61A1', 'PPP1R12A', 'RASGRF1', 'CAMK2B', 'CROCC', 'POLR3E', 'ATP2B4', 'ZC3H11A', 'RIOK2', 'YIPF1', 'NDC1', 'DGKG', 'FLYWCH1', 'UNKL', 'TBXAS1', 'PARP12', 'ALDH18A1', 'TARBP1', 'GATB', 'MXD1', 'CDK17', 'DNAJC25', 'SLC2A3', 'PSD', 'CTDP1', 'YBX3', 'STYK1', 'WNK1', 'CCAR1', 'OGFR', 'GNA15', 'CREB3L3', 'PIGV', 'PTPRU', 'SNRNP40', 'RIMBP2', 'COL11A1', 'QSER1', 'MPC1', 'ACAA1', 'BCAT1', 'HDAC7', 'LZTS1', 'PRDM6', 'WNT8A', 'SPAG4', 'NCKAP1', 'MRPS35', 'GUCY1B3', 'SFSWAP', 'TNK2', 'MON2', 'CDH3', 'ARSF', 'GPBP1', 'DGAT2', 'ZNF112', 'CS', 'LTK', 'MRPS24', 'ELMO2', 'WAPL', 'VMP1', 'APPBP2', 'POLD1', 'SEZ6', 'EIF4B', 'SLC6A16', 'BICRA', 'SPHK2', 'RPL18', 'CA11', 'ISOC2', 'U2AF2', 'EPN1', 'MED29', 'AHRR', 'GSC2', 'ZNF275', 'MTMR1', 'GPC1', 'ADCK1', 'HAGH', 'RNF4', 'CASP8', 'LIMCH1', 'INTS13', 'TM7SF3', 'DLX3', 'SPA17', 'TSPAN32', 'WISP2', 'DMRT3', 'ST3GAL6', 'ATP2C2', 'NGFR', 'CDON', 'TAF2', 'HIPK2', 'TNPO3', 'BORCS8-MEF2B', 'RFXANK', 'TMEM161A', 'LPAR2', 'CTSA', 'SUGP2', 'SLC12A2', 'SNX24', 'EYA2', 'CNN2', 'ABCA7', 'SNCAIP', 'DDX20', 'BTBD1', 'FAR2', 'BCAS1', 'POU1F1', 'CHI3L2', 'SBNO2', 'PMS1', 'HMG20B', 'CALCRL', 'TAF11', 'ANKS1A', 'AP3D1', 'ZNF76', 'SLC9A3R2', 'NTHL1', 'UHRF1BP1', 'GNAI3', 'IPO5', 'OAT', 'WDR3', 'PKN2', 'WDR18', 'TRAM2', 'NTN1', 'GLP2R', 'MCM10', 'DGKA', 'ERBB3', 'ROPN1', 'ANKRD44', 'KARS', 'ADAT1', 'PDIA5', 'TBC1D22B', 'NDUFB4', 'SPEN', 'MYLK', 'ZC3H15', 'MAP2K4', 'TMEM206', 'SNAP91', 'SLK', 'CYB5R4', 'COL17A1', 'GSTO2', 'SEC61A2', 'PRKCQ', 'TLE2', 'ASB1', 'FAM107B', 'ME1', 'TBC1D1', 'CDK13', 'MTHFD2', 'SLC9A7', 'FOXJ2', 'YBX1', 'PDE4A', 'PPP2R5A', 'CTNNA2', 'ELAVL1', 'TIE1', 'DIP2B', 'SMARCD1', 'KDM4A', 'NFYC', 'ZMYND12', 'SLC9A3', 'NGEF', 'ASPM', 'CD84', 'ELOVL1', 'SPI1', 'ZNRD1', 'MPPED2', 'CLDN18', 'ZBTB11', 'ATXN3', 'GOLGA5', 'FGFR2', 'LRRC40', 'ISOC1', 'EML1', 'TRMT11', 'THUMPD1', 'MSANTD3', 'KIF26A', 'ATG2B', 'ARFGEF1', 'ACSM2B', 'ZFAT', 'MTFR1', 'STAG3', 'FECH', 'MYO9A', 'DDX3Y', 'PFKP', 'IDI1', 'SP100', 'KLF6', 'PLPP1', 'NEO1', 'TRAM1', 'PHKA1', 'TNFRSF1A', 'CACNB1', 'EVI5', 'STOML1', 'PKM', 'DHX29', 'DNTTIP2', 'METTL22', 'TP53BP1', 'TRO', 'RRP15', 'RHOA', 'DHX8', 'PRKCZ', 'ZFY', 'IARS2', 'SYT1', 'NAV3', 'IDH3G', 'ROGDI', 'PDZD4', 'ATP2B3', 'ROCK1', 'CBFB', 'PDK3', 'HYAL2', 'HDAC4', 'RASSF1', 'FGFR3', 'IFI35', 'HEATR6', 'COASY', 'PLEKHH3', 'MEF2A', 'OTUD5', 'TFE3', 'TBC1D25', 'ACSL4', 'INPP5A', 'GPKOW', 'GRIPAP1', 'FTSJ1', 'PRR11', 'REEP1', 'ATP11A', 'POLR1A', 'LAPTM4A', 'TTC7A', 'IP6K2', 'STON1-GTF2A1L', 'SRBD1', 'KIF2A', 'RASGRP2', 'PSME4', 'IFT80', 'SIRT2', 'ERLEC1', 'PPP2R5B', 'PYGM', 'PAGE1', 'PITX1', 'TRPC7', 'MAST4', 'ADGRF5', 'SDK2', 'ADAM7', 'NUP133', 'NUCKS1', 'VPS35', 'DNAJA2', 'BCL3', 'KCNAB2', 'ABCC9', 'GAL', 'CLEC2D', 'FUNDC1', 'MAOB', 'RORA', 'DRD4', 'TGFBR3', 'KIAA1107', 'PLA2G10', 'HES2', 'ATP1B3', 'NEDD4', 'PIGB', 'MAPK6', 'GNB5', 'RAB27A', 'HDHD5', 'UFD1', 'LRP6', 'GUCY2C', 'SCT', 'PHRF1', 'IKBKAP', 'NUCB2', 'PFN2', 'PTPN3', 'SPTB', 'DAPP1', 'FGF10', 'SLC44A1', 'TMEM260', 'SMG6', 'EXOC5', 'CLTCL1', 'FGF22', 'FSTL3', 'DGCR2', 'RNF126', 'MNT', 'ZXDC', 'JMJD6', 'POLB', 'ST6GALNAC1', 'WIPI1', 'FRMPD1', 'GBA2', 'NDST1', 'ASNS', 'AP3M2', 'CNGB1', 'ST6GALNAC2', 'CHAT', 'PABPC1', 'TESK2', 'CFAP20', 'CSNK2A2', 'PTPN21', 'EIF2B3', 'CAMK2A', 'TCOF1', 'CDC42', 'OSBPL3', 'EPHA8', 'SLC12A3', 'RAD18', 'ATP2B1', 'TRPM5', 'NCK2', 'MAP4K4', 'MGAT4A', 'RPL31', 'WDR1', 'SNX13', 'MS4A12', 'ARHGAP10', 'RPS6KA2', 'ING3', 'VASH1', 'LMCD1', 'BUD23', 'SEL1L', 'TRIP13', 'ATP6AP1', 'TCF3', 'TRIB2', 'DAZAP1', 'MBD3', 'PRLH', 'HLTF', 'FAM50A', 'FAM3A', 'CPSF1', 'MYO3B', 'CYBRD1', 'CDH19', 'PDCD2', 'SLC6A15', 'RDH11', 'PRKACA', 'ADGRL1', 'SPP2', 'ACTN1', 'ZFYVE26', 'RPS6KA6', 'EPN2', 'PTPN18', 'LIMS2', 'ASIC4', 'SPEG', 'LNX1', 'ALDH3A2', 'TFRC', 'SREBF1', 'TRPC5', 'AFF4', 'UBE2D1', 'MPP5', 'RHOBTB1', 'SMC1A', 'HSD17B10', 'MARK2', 'HMMR', 'CHFR', 'TRHDE', 'P4HA2', 'FCGR2B', 'NFATC3', 'TRNT1', 'ACADVL', 'STK10', 'FBXW11', 'ACAP1', 'CRMP1', 'EVC', 'DERL2', 'SIDT1', 'NDE1', 'MRVI1', 'TMEM38A', 'AP1M1', 'PVR', 'XRCC1', 'SCARB1', 'CYP2W1', 'MCM2', 'MOV10L1', 'PANX2', 'SELENOO', 'TP63', 'ALPK1', 'LLGL2', 'PDE8A', 'CLCN4', 'NLE1', 'SDHA', 'SMARCE1', 'FNDC8', 'GSDMB', 'KDM5A', 'ADAM11', 'PPP2R3A', 'FERMT2', 'ABCB11', 'DHRS9', 'CD5L', 'PTGS2', 'IGF2BP2', 'MAP3K13', 'ST6GAL1', 'TBX21', 'FRY', 'PICALM', 'NSF', 'GLI2', 'CLASP1', 'MRPS34', 'NOTCH3', 'CLNS1A', 'PPP2R2C', 'TEAD2', 'EED', 'CDHR2', 'SNCB', 'TSG101', 'NCBP3', 'ATP2A3', 'CA12', 'MGLL', 'NTN4', 'BCS1L', 'NUAK1', 'DPP8', 'SLC24A1', 'ZNF532', 'SCARF1', 'LMAN1', 'HACD3', 'IPCEF1', 'ZZEF1', 'NOX3', 'ENO1', 'SLC12A1', 'MYDGF', 'ANO8', 'TUBE1', 'ARHGEF10L', 'TXK', 'WSCD2', 'KCNQ2', 'TACR2', 'ACTR6', 'TIPIN', 'SRI', 'EIF4G3', 'NUP37', 'SEMA3A', 'GTSE1', 'SEMA3C', 'TTC38', 'ACAT1', 'GRAMD4', 'CELSR1', 'WNT8B', 'ZNF638', 'SLC25A40', 'TIMM21', 'ADD2', 'FGF4', 'RASAL2', 'VPS9D1', 'ZNF37A', 'MARK3', 'SLC25A3', 'FNDC3B', 'FOSL2', 'CACNG5', 'CACNG4', 'FRYL', 'TMEM131', 'FSCN1', 'ACTB', 'MOCOS', 'PLD1', 'ATP12A', 'WDR62', 'DLG1', 'RAB7A', 'BCAP29', 'SEC31B', 'SART3', 'ARHGAP15', 'TUBA3D', 'PAX2', 'EXOSC7', 'KIFAP3', 'MKRN2', 'MCM6', 'REXO2', 'RBM7', 'RBMS2', 'BAZ2A', 'PTPN23', 'MLH1', 'UNG', 'FMO4', 'KLHL20', 'RGS11', 'SLC46A1', 'PLXNA2', 'SPAG5', 'ANKRD13A', 'TPD52', 'ACACB', 'TRAF4', 'PAG1', 'GPATCH1', 'ICAM3', 'NT5C2', 'MCAM', 'GPC4', 'MBNL3', 'CAMSAP3', 'RAP1GAP', 'XAB2', 'ARHGEF1', 'STXBP2', 'MAP2K7', 'NMRK2', 'DGKD', 'CTTNBP2', 'ACTL6B', 'RARB', 'TOP2B', 'TM9SF3', 'NFKB2', 'UBE2T', 'PPP1R12B', 'DNAJC10', 'GTF3C1', 'IL4R', 'USP33', 'PAK3', 'CAPN6', 'DCX', 'SNRPA', 'SPAG6', 'EXOSC5', 'DYNC1I2', 'APBB1IP', 'LRCH4', 'FAM76B', 'SIRT6', 'TYR', 'POLD3', 'ACTN2', 'CAPZB', 'GPR137B', 'NAALAD2', 'JADE1', 'SLC25A43', 'UBE2A', 'FGFR1', 'FKBP6', 'SMC1B', 'FBLN1', 'ITGA8', 'CST7', 'MAP2', 'PIAS2', 'AMPH', 'ARAF', 'MCCC1', 'LAMP3', 'FAP', 'NEBL', 'ACER3', 'UBE2K', 'PIK3C3', 'N4BP2', 'TIGAR', 'TULP3', 'SYNJ2', 'ADCY2', 'PPP2R5C', 'RBFOX1', 'GNB1', 'HOXA9', 'EDN1', 'MLLT10', 'ZCWPW1', 'ADCYAP1R1', 'FGF20', 'P2RY10', 'ITM2A', 'NRDC', 'VDAC3', 'PCM1', 'TNRC6C', 'CBFA2T2', 'BRINP1', 'ITCH', 'PKD2L2', 'TP53INP2', 'SDF4', 'MYH7B', 'BPIFB2', 'TP73', 'TOLLIP', 'UBE2D4', 'CLUL1', 'RUNX1T1', 'CDH17', 'THOC1', 'FKBP7', 'OSBPL6', 'SLC1A3', 'XRCC5', 'LXN', 'SP140', 'MKNK1', 'TNS1', 'REXO1', 'SAR1A', 'CDC14A', 'RAPGEF3', 'CEACAM1', 'SENP1', 'DUSP13', 'CIC', 'LIPE', 'FDFT1', 'PAFAH1B3', 'OPHN1', 'AFM', 'KIF22', 'SCGN', 'CARMIL1', 'PGM1', 'DDX1', 'DNM2', 'EPB41L2', 'RIMS1', 'MOXD1', 'STX7', 'RABL2B', 'KEAP1', 'DDX43', 'PTPRH', 'DCT', 'SLC35C2', 'CRYBG3', 'EPHA6', 'SCTR', 'RFX3', 'RIF1', 'RAB21', 'SLC4A4', 'SMARCA2', 'RDH8', 'SESN1', 'MID2', 'PIH1D3', 'COL5A3', 'SRCAP', 'PUM3', 'CPB2', 'CHRNA3', 'KCNN2', 'CNOT4', 'PSEN1', 'CPOX', 'CLDND1', 'MOK', 'HSP90AA1', 'RBL1', 'DLGAP4', 'IGSF9B', 'CFHR2', 'CROCCP3', 'NDC80', 'AP4E1', 'RSBN1', 'MAGI3', 'CXCL2', 'AFP', 'COL4A4', 'TCF7', 'OSTM1', 'CDH7', 'IMPG2', 'PCNP', 'EXD2', 'ARG2', 'MEF2C', 'PTPRC', 'CACNA1S', 'PKP1', 'UBA5', 'STK17B', 'CDC14B', 'ZNF510', 'LRP2', 'ZNF506', 'JMJD4', 'DUSP12', 'AACS', 'KIAA0141', 'SLC13A1', 'CADPS2', 'PCDHB4', 'PCDHA6', 'PCDHGA2', 'HSPB11', 'PHLPP1', 'ATP8B1', 'IL12RB2', 'SMARCD3', 'WDR70', 'FYB', 'MPP4', 'STRADB', 'BZW1', 'PGR', 'C1QTNF3', 'ME2', 'C5orf22', 'CCNT2', 'FAM135A', 'COL19A1', 'EPB41L3', 'COBLL1', 'DLG3', 'KCNK2', 'SERTAD4', 'TRAF5', 'MRPL22', 'GEMIN5', 'OPRK1', 'NFE2L1', 'SEMA5B', 'GSK3B', 'ITGB5', 'ERC1', 'XPO1', 'LINC01587', 'RNF13', 'TRPM3', 'PALB2', 'DOPEY1', 'LYRM2', 'BCKDHB', 'KAT6A', 'ZCCHC6', 'ULK2', 'GRHL2', 'TNPO1', 'PLOD1', 'P2RX5', 'ITGAE', 'DIS3', 'PIBF1', 'TDRD3', 'NUFIP1', 'PDS5B', 'OXCT1', 'RRAGB', 'EPYC', 'CYLD', 'SLC27A5', 'ZNF324', 'ZNF671', 'ZNF416', 'ZNF586', 'ZNF446', 'ZNF264', 'RPS5', 'FAT1', 'YTHDC1', 'CHMP2B', 'SMAP2', 'PPIE', 'ZMPSTE24', 'STARD7', 'NOA1', 'REST', 'HAL', 'SSH1', 'GSTP1', 'APLP2', 'FAM234B', 'SLCO1A2', 'WBP11', 'EIF3I', 'NKAIN1', 'COL16A1', 'TXLNA', 'APOB', 'NCOA1', 'AGBL5', 'EFR3B', 'KIF3C', 'RAB10', 'GCKR', 'HADHA', 'MAPRE3', 'CAD', 'CD59', 'CD82', 'BCORL1', 'ATRX', 'AK6', 'FCN1', 'MYNN', 'MECOM', 'SCAMP1', 'PREP', 'HACE1', 'SEH1L', 'WDR47', 'WDFY1', 'OVGP1', 'SLC25A24', 'MAP3K4', 'PILRA', 'IGSF9', 'ABCB1', 'ZNF213', 'AKR1B1', 'CPNE3', 'RRN3', 'CTTN', 'WNT11', 'MTIF2', 'DDHD2', 'TTC39A', 'EPS15', 'ORC1', 'MGST2', 'CHERP', 'ATG16L1', 'USP40', 'POMGNT1', 'RAD54L', 'MAST2', 'DNAJA1', 'B4GALT1', 'CHMP5', 'NFX1', 'AQP6', 'DIMT1', 'IPO11', 'FOLH1', 'EIF2AK1', 'NME8', 'EPDR1', 'SNX10', 'SEPHS1', 'MRPL28', 'HBQ1', 'ITPKC', 'CEACAM6', 'FAT2', 'RBM22', 'TMED2', 'ERO1B', 'ZFAND6', 'HSD17B2', 'TXLNG', 'PPEF1', 'LAT2', 'HUWE1', 'ZW10', 'ALG9', 'MYBPC2', 'NOX4', 'ACOX3', 'MTMR2', 'PPP1R15A', 'HSD17B14', 'TRIP6', 'ACHE', 'FTL', 'SRRT', 'BAX', 'NLK', 'PIGS', 'ADAMTS2', 'TMPRSS11E', 'ATXN7L3', 'PGS1', 'PSMC5', 'UIMC1', 'CETP', 'MMP2', 'MT3', 'LPCAT2', 'GNAO1', 'OGFOD1', 'SH3BP2', 'NOP14', 'ADD1', 'L2HGDH', 'TXNDC16', 'C14orf166', 'NID2', 'GMCL1', 'SF3B2', 'KLHL42', 'GNAS', 'DNM1L', 'PTHLH', 'PHACTR3', 'ERGIC2', 'TFAP2C', 'AURKA', 'CASS4', 'PIR', 'AAMDC', 'RFX2', 'METTL2A', 'SULT2B1', 'ALG6', 'CNOT3', 'GP6', 'PTPN4', 'DDX18', 'KHSRP', 'GNA11', 'ASAP3', 'EDEM2', 'DNMT3B', 'REM1', 'TPX2', 'FER1L4', 'PDRG1', 'EPB41L1', 'SLC15A1', 'DOCK9', 'ANKRD10', 'TGDS', 'DOCK3', 'C3orf18', 'COQ9', 'TMEM40', 'KIF9', 'ARHGAP28', 'CRLS1', 'DEFB127', 'PPP1R13B', 'ATRN', 'SMOX', 'SIGLEC1', 'FKBP1A', 'NSFL1C', 'SLC4A11', 'C20orf194', 'ZNF343', 'EBF4', 'CPXM1', 'MAVS', 'LZTS3', 'F11', 'XRN2', 'KIZ', 'DYNLL1', 'TESC', 'SNX5', 'RPL6', 'SIRPG', 'MAPKAPK5', 'P2RX7', 'ESF1', 'RBBP9', 'ANAPC5', 'SLC23A2', 'SLC8B1', 'TMEM230', 'DZANK1', 'KDM2B', 'CFAP61', 'LHX5', 'TASP1', 'OAS1', 'GCN1', 'RPLP0', 'PXN', 'SIRT4', 'RPH3A', 'KIF16B', 'TRMT6', 'CHGB', 'PEBP1', 'TBX5', 'BRAP', 'ERP29', 'NOS1', 'FUS', 'IGBP1', 'FXYD5', 'ZNF302', 'GRAMD1A', 'FXYD3', 'HEPH', 'CDIP1', 'CMTM1', 'KCNH4', 'GANAB', 'GMIP', 'RBM41', 'BIRC5', 'LAG3', 'MLF2', 'OTUB2', 'DDX24', 'ZBTB25', 'NECAP1', 'ARHGAP4', 'ANKRD24', 'DHX32', 'RCOR1', 'GPATCH2L', 'LTBP4', 'BLVRB', 'SLC9A1', 'SPTLC1', 'PAPOLA', 'CCNK', 'PCBP4', 'RGS1', 'YPEL3', 'MRPS33', 'NDUFB2', 'NUDC', 'MAEA', 'ICAM1', 'STRN4', 'IRAK3', 'LYZ', 'SI', 'MUL1', 'TFAP4', 'PDCD7', 'SPG21', 'FETUB', 'DNAJB11', 'P3H2', 'THPO', 'CHRD', 'FLT3LG', 'RAB11FIP3', 'GNPTG', 'ZNF268', 'GOLGA3', 'PABPC4', 'CD209', 'CERS4', 'MCOLN1', 'USP48', 'EFNB1', 'PDPR', 'AARS', 'GLG1', 'KIF4A', 'TNRC6A', 'PLEKHG2', 'DLL3', 'NAT14', 'PITPNM2', 'EXOC1', 'RBM27', 'POU4F3', 'OSBPL8', 'DTX2', 'NLRC4', 'PUS7', 'LAMB4', 'NRCAM', 'LAMB1', 'SLC26A4', 'SLC26A3', 'DLD', 'WDR7', 'TXNL1', 'IL5RA', 'ABCC6', 'CMTM6', 'ITGA6', 'RAPGEF4', 'MAP3K20', 'SMPX', 'FH', 'SEL1L3', 'TF', 'CDV3', 'MYO15A', 'ALKBH5', 'APOH', 'NLRP1', 'PITPNM3', 'SPAG7', 'ORC6', 'ZFHX4', 'SLC17A6', 'CPA1', 'ZC3HC1', 'ESR1', 'RGS17', 'ANGPT2', 'TMEM101', 'CD200', 'CCDC80', 'CMA1', 'PSME1', 'PPP2R3C', 'HAUS4', 'JPH4', 'MYH7', 'CEBPE', 'SLC7A8', 'OSGEP', 'SLC22A17', 'RNF31', 'SCFD1', 'G2E3', 'HECTD1', 'HNRNPC', 'RPGRIP1', 'SUPT16H', 'TOX4', 'GEMIN2', 'TGM1', 'TINF2', 'DAZL', 'TBL1Y', 'SEMA6A', 'TRPM7', 'TYRO3', 'WDR76', 'CAPN3', 'SNAP23', 'TBX15', 'PHGDH', 'COL9A3', 'EZR', 'MYL6', 'AGO1', 'TEKT2', 'CLSPN', 'RFFL', 'UNC13D', 'MFSD11', 'DPYSL2', 'TGFB2', 'GPATCH2', 'NUP50', 'CDC45', 'COMT', 'ADA2', 'VNN3', 'ECHDC1', 'LRRFIP2', 'SEC22C', 'XYLB', 'HDAC6', 'OR1I1', 'GABRP', 'KRT31', 'CDC6', 'UPRT', 'CDC23', 'AAAS', 'CBX5', 'FMO2', 'SUCO', 'MSH2', 'MAP3K1', 'DHPS', 'HOOK2', 'NXPE1', 'ARCN1', 'EPB41L4B', 'TMEM38B', 'PSMD5', 'PTGS1', 'NUP188', 'CRAT', 'SH2D3C', 'NANS', 'TBC1D2', 'WHRN', 'PDE6C', 'CWF19L1', 'SEMA4G', 'BTAF1', 'IKZF5', 'BLNK', 'TLL2', 'CYP26A1', 'TDRD1', 'SORBS1', 'CRTAC1', 'BAMBI', 'IL11', 'MYO3A', 'WAC', 'CREM', 'NUBP2', 'TPSD1', 'SMIM24', 'HIVEP1', 'TREM2', 'KCNK16', 'CRISP3', 'FKBP5', 'SRPK1', 'BRPF3', 'MRPS18A', 'PGC', 'TMEM14A', 'EFHC1', 'RPS18', 'BAG6', 'VARS', 'NCR2', 'HSP90AB1', 'MLN', 'CDC5L', 'ITPR3', 'ZNF184', 'DSP', 'SIRT1', 'HNRNPH3', 'IFT74', 'JAK2', 'IL12RB1', 'ABL1', 'ACOT7', 'SH3GLB1', 'CDC7', 'SYDE2', 'PCSK5', 'SCD', 'TMED1', 'ABLIM1', 'ERMP1', 'RAB18', 'NRP1', 'HSD17B7P2', 'PRTFDC1', 'PALMD', 'TSPAN15', 'H2AFY2', 'WASHC2A', 'MAST3', 'MZF1', 'OCEL1', 'MYO9B', 'KCNK6', 'CATSPERG', 'PSMD8', 'FBXL19', 'STX1B', 'HSD3B7', 'SETD1A', 'BCL7C', 'MAGEB2', 'EFNA2', 'CIRBP', 'ATP5D', 'CBARP', 'PCDH11X', 'AMELY', 'PRKY', 'IGFALS', 'HNRNPM', 'MARCH2', 'NDUFB7', 'TECR', 'TIMM13', 'CDC34', 'MTAP', 'MISP', 'CEP170B', 'POLR2E', 'POLRMT', 'HCN2', 'CDHR5', 'IZUMO4', 'RASSF7', 'GADD45B', 'PALM', 'MADCAM1', 'IGF2-AS', 'MKNK2', 'ARVCF', 'TRMT2A', 'RANBP1', 'ZDHHC8', 'KLHL22', 'MED15', 'SERPIND1', 'SNAP29', 'CRKL', 'LZTR1', 'MMP11', 'CECR2', 'SMARCB1', 'P2RX6', 'DERL3', 'SLC7A4', 'BCL2L13', 'DDTL', 'DDT', 'GSTT2', 'OSM', 'CABIN1', 'TBC1D10A', 'SUSD2', 'SF3A1', 'GGT5', 'RNF215', 'SEC14L2', 'SEC14L3', 'SPECC1L', 'PPIL2', 'UPB1', 'YPEL1', 'SNRPD3', 'PES1', 'MAPK1

In [ ]:
from statsmodels.stats.multitest import multipletests

# Assuming you have raw p-values in `combined_sig_genes["p_value"]`
_, adj_pvals, _, _ = multipletests(combined_sig_genes["p_value"], method='fdr_bh')
combined_sig_genes["adj_p_value"] = adj_pvals

In [ ]:
# --- Statistical Significance: p-value ---
p_values = [ttest_ind(group1[col], group2[col], equal_var=False).pvalue for col in gene_expression.columns]
pval_df = pd.DataFrame({"Gene": gene_expression.columns, "p_value": p_values})

In [ ]:
from statsmodels.stats.multitest import multipletests

# --- Statistical Significance: p-value + adjusted p-value ---
p_values = [ttest_ind(group1[col], group2[col], equal_var=False).pvalue for col in gene_expression.columns]
adjusted_pvals = multipletests(p_values, method='fdr_bh')[1]
pval_df = pd.DataFrame({
    "Gene": gene_expression.columns,
    "p_value": p_values,
    "adj_p_value": adjusted_pvals
})

In [ ]:
final_deg_df = combined_sig_genes[["Gene", "log2fc", "p_value", "adj_p_value", "Target"]]

In [ ]:
final_deg_df = combined_sig_genes[["Gene", "log2fc", "p_value", "adj_p_value", "Target"]]

In [ ]:
final_deg_df

               Gene    log2fc       p_value   adj_p_value  Target
5               FGR  2.312334  1.424200e-08  3.656048e-07       1
13            ENPP4  1.055971  3.509842e-02  4.016773e-02       1
65              ST7 -1.883971  1.298770e-05  1.371826e-04       0
116          OSBPL7 -1.201447  3.824219e-04  1.882407e-03       0
122          CACNG3 -1.255598  1.077081e-04  7.161705e-04       0
...             ...       ...           ...           ...     ...
27960       MIR7515  2.000880  4.434787e-02  4.647932e-02       1
28015  LOC101929989 -1.143389  4.102652e-02  4.439796e-02       0
28023         ACR.1 -1.120220  1.215591e-02  2.073354e-02       0
28056       SYT14.1 -1.124801  5.214655e-03  1.205852e-02       0
28073       MIR3974 -2.416112  4.873712e-02  4.939475e-02       0

[2028 rows x 5 columns]

In [ ]:
# Make sure log2FC column is absolute for sorting
combined_sig_genes["abs_log2FC"] = combined_sig_genes["log2fc"].abs()

# Sort by absolute log2 fold change
top_150_degs = combined_sig_genes.sort_values(by="abs_log2FC", ascending=False).head(150)

# Drop the helper column if you want
top_150_degs = top_150_degs.drop(columns=["abs_log2FC"])

# Save to CSV (optional)
top_150_degs.to_csv("Top_150_DEGs_by_log2FC.csv", index=False)

# Print summary
print("Top 150 DEGs selected based on absolute log2 fold change (|log2FC|):")
print(top_150_degs[["Gene", "log2fc", "p_value", "adj_p_value", "Target"]].head())

Top 150 DEGs selected based on absolute log2 fold change (|log2FC|):
            Gene    log2fc   p_value  adj_p_value  Target
27004  TBC1D3H.1 -9.047748  0.048561     0.049331       0
25918    TBC1D3H -9.047748  0.048561     0.049331       0
24109    TBC1D3G -9.043913  0.049162     0.049712       0
26388  TBC1D3G.1 -9.043913  0.049162     0.049712       0
27311   OR4N3P.2 -8.511147  0.045430     0.047199       0

In [ ]:
Top_150_DEGs=pd.read_csv("/content/Top_150_DEGs_by_log2FC.csv")

In [ ]:
Top_150_DEGs

          Gene   p_value    log2fc  Combined_Significant  Target  adj_p_value
0    TBC1D3H.1  0.048561 -9.047748                  True       0     0.049331
1      TBC1D3H  0.048561 -9.047748                  True       0     0.049331
2      TBC1D3G  0.049162 -9.043913                  True       0     0.049712
3    TBC1D3G.1  0.049162 -9.043913                  True       0     0.049712
4     OR4N3P.2  0.045430 -8.511147                  True       0     0.047199
..         ...       ...       ...                   ...     ...          ...
145      RSAD2  0.006387 -2.824846                  True       0     0.013813
146  VWC2L-IT1  0.011494 -2.823282                  True       0     0.020043
147      LTA.5  0.000003 -2.813293                  True       0     0.000038
148      LTA.4  0.000003 -2.813236                  True       0     0.000038
149      LTA.3  0.000003 -2.813231                  True       0     0.000038

[150 rows x 6 columns]

In [ ]:
final_150_deg = Top_150_DEGs[["Gene", "log2fc", "p_value", "adj_p_value", "Target"]]

In [ ]:
final_150_deg

          Gene    log2fc   p_value  adj_p_value  Target
0    TBC1D3H.1 -9.047748  0.048561     0.049331       0
1      TBC1D3H -9.047748  0.048561     0.049331       0
2      TBC1D3G -9.043913  0.049162     0.049712       0
3    TBC1D3G.1 -9.043913  0.049162     0.049712       0
4     OR4N3P.2 -8.511147  0.045430     0.047199       0
..         ...       ...       ...          ...     ...
145      RSAD2 -2.824846  0.006387     0.013813       0
146  VWC2L-IT1 -2.823282  0.011494     0.020043       0
147      LTA.5 -2.813293  0.000003     0.000038       0
148      LTA.4 -2.813236  0.000003     0.000038       0
149      LTA.3 -2.813231  0.000003     0.000038       0

[150 rows x 5 columns]

In [ ]:
final_150_deg ['Target'].value_counts()

Target
0    141
1      9
Name: count, dtype: int64

In [ ]:
final_150_deg.to_csv('/content/drive/My Drive/Data_Set/DENV_gene/final_150_degs.csv')

In [ ]:
Final_DEGs=pd.read_csv("/content/drive/MyDrive/Data_Set/DENV_gene/DEGs_Final.csv")

In [ ]:
Final_DEGs

,Unnamed: 0,Gene,0,1,2,3,4,5,6,7,...,2237,2238,2239,2240,2241,2242,2243,log2fc,p_value,target
0,0,FGR,0.0000,0.0000,0.0000,0.000,2.9110,16.9374,0.000,1.2777,...,4.0247,19.8922,18.1169,0.0000,0.0,0.0000,8.6683,2.312334,1.424200e-08,1.0
1,1,ENPP4,2.8671,11.4588,0.0000,0.000,13.4420,0.0000,0.000,617.6932,...,0.0000,0.8117,0.0000,60.5167,0.0,0.0000,0.0000,1.055971,3.509842e-02,1.0
2,2,ST7,9.6391,44.6741,48.9423,50.224,45.3135,0.0000,87.121,0.7783,...,6.2787,0.0000,9.3375,15.3363,0.0,4.3941,7.8650,-1.883971,1.298770e-05,0.0
3,3,OSBPL7,0.0000,0.3913,10.5258,0.000,6.4898,1.5395,0.000,0.0000,...,797.1408,279.1432,6.5387,0.6939,0.0,2.4243,2.8046,-1.201447,3.824219e-04,0.0
4,4,CACNG3,0.0000,0.8965,0.0000,0.000,2.4045,0.0000,0.000,0.0000,...,0.0000,0.0000,0.8075,0.0000,0.0,0.0000,0.0000,-1.255598,1.077081e-04,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023,2023,MIR7515,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,2.000880,4.434787e-02,1.0
2024,2024,LOC101929989,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,32.7870,0.0,0.0000,0.0000,-1.143389,4.102652e-02,0.0
2025,2025,ACR.1,0.0000,0.0000,0.0000,0.228,0.0000,2.0852,0.000,4.7458,...,0.0000,0.0000,0.0000,0.0000,0.0,2.5423,0.3553,-1.120220,1.215591e-02,0.0
2026,2026,SYT14.1,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,9.1070,0.0000,0.0,0.0000,0.0000,-1.124801,5.214655e-03,0.0
2027,2027,MIR3974,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,-2.416112,4.873712e-02,0.0

In [ ]:
DFM = pd.merge(Final_DEGs, final_deg_df[["Gene", "adj_p_value"]], on="Gene", how="left")

In [ ]:
DFM

,Unnamed: 0,Gene,0,1,2,3,4,5,6,7,...,2238,2239,2240,2241,2242,2243,log2fc,p_value,target,adj_p_value
0,0,FGR,0.0000,0.0000,0.0000,0.000,2.9110,16.9374,0.000,1.2777,...,19.8922,18.1169,0.0000,0.0,0.0000,8.6683,2.312334,1.424200e-08,1.0,3.656048e-07
1,1,ENPP4,2.8671,11.4588,0.0000,0.000,13.4420,0.0000,0.000,617.6932,...,0.8117,0.0000,60.5167,0.0,0.0000,0.0000,1.055971,3.509842e-02,1.0,4.016773e-02
2,2,ST7,9.6391,44.6741,48.9423,50.224,45.3135,0.0000,87.121,0.7783,...,0.0000,9.3375,15.3363,0.0,4.3941,7.8650,-1.883971,1.298770e-05,0.0,1.371826e-04
3,3,OSBPL7,0.0000,0.3913,10.5258,0.000,6.4898,1.5395,0.000,0.0000,...,279.1432,6.5387,0.6939,0.0,2.4243,2.8046,-1.201447,3.824219e-04,0.0,1.882407e-03
4,4,CACNG3,0.0000,0.8965,0.0000,0.000,2.4045,0.0000,0.000,0.0000,...,0.0000,0.8075,0.0000,0.0,0.0000,0.0000,-1.255598,1.077081e-04,0.0,7.161705e-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023,2023,MIR7515,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,2.000880,4.434787e-02,1.0,4.647932e-02
2024,2024,LOC101929989,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,32.7870,0.0,0.0000,0.0000,-1.143389,4.102652e-02,0.0,4.439796e-02
2025,2025,ACR.1,0.0000,0.0000,0.0000,0.228,0.0000,2.0852,0.000,4.7458,...,0.0000,0.0000,0.0000,0.0,2.5423,0.3553,-1.120220,1.215591e-02,0.0,2.073354e-02
2026,2026,SYT14.1,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,9.1070,0.0000,0.0,0.0000,0.0000,-1.124801,5.214655e-03,0.0,1.205852e-02
2027,2027,MIR3974,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,-2.416112,4.873712e-02,0.0,4.939475e-02

In [ ]:
# Move 'Target' column to the end
target_col = DFM .pop("target")  # Remove and store the 'Target' column
DFM["target"] = target_col      # Add it back at the end

# Save to CSV (optional)
DFM.to_csv("DEGs_set.csv", index=False)

# Print summary
print("DEGs_set (Target column moved to end):")
print(DFM .head())

DEGs_set (Target column moved to end):
   Unnamed: 0    Gene       0        1        2       3        4        5  \
0           0     FGR  0.0000   0.0000   0.0000   0.000   2.9110  16.9374
1           1   ENPP4  2.8671  11.4588   0.0000   0.000  13.4420   0.0000
2           2     ST7  9.6391  44.6741  48.9423  50.224  45.3135   0.0000
3           3  OSBPL7  0.0000   0.3913  10.5258   0.000   6.4898   1.5395
4           4  CACNG3  0.0000   0.8965   0.0000   0.000   2.4045   0.0000

        6         7  ...      2238     2239     2240  2241    2242    2243  \
0   0.000    1.2777  ...   19.8922  18.1169   0.0000   0.0  0.0000  8.6683
1   0.000  617.6932  ...    0.8117   0.0000  60.5167   0.0  0.0000  0.0000
2  87.121    0.7783  ...    0.0000   9.3375  15.3363   0.0  4.3941  7.8650
3   0.000    0.0000  ...  279.1432   6.5387   0.6939   0.0  2.4243  2.8046
4   0.000    0.0000  ...    0.0000   0.8075   0.0000   0.0  0.0000  0.0000

     log2fc       p_value   adj_p_value  target
0  2.312334  1.424200e-08  3.656048e-07     1.0
1  1.055971  3.509842e-02  4.016773e-02     1.0
2 -1.883971  1.298770e-05  1.371826e-04     0.0
3 -1.201447  3.824219e-04  1.882407e-03     0.0
4 -1.255598  1.077081e-04  7.161705e-04     0.0

[5 rows x 2250 columns]

In [ ]:
DFM

,Unnamed: 0,Gene,0,1,2,3,4,5,6,7,...,2238,2239,2240,2241,2242,2243,log2fc,p_value,adj_p_value,target
0,0,FGR,0.0000,0.0000,0.0000,0.000,2.9110,16.9374,0.000,1.2777,...,19.8922,18.1169,0.0000,0.0,0.0000,8.6683,2.312334,1.424200e-08,3.656048e-07,1.0
1,1,ENPP4,2.8671,11.4588,0.0000,0.000,13.4420,0.0000,0.000,617.6932,...,0.8117,0.0000,60.5167,0.0,0.0000,0.0000,1.055971,3.509842e-02,4.016773e-02,1.0
2,2,ST7,9.6391,44.6741,48.9423,50.224,45.3135,0.0000,87.121,0.7783,...,0.0000,9.3375,15.3363,0.0,4.3941,7.8650,-1.883971,1.298770e-05,1.371826e-04,0.0
3,3,OSBPL7,0.0000,0.3913,10.5258,0.000,6.4898,1.5395,0.000,0.0000,...,279.1432,6.5387,0.6939,0.0,2.4243,2.8046,-1.201447,3.824219e-04,1.882407e-03,0.0
4,4,CACNG3,0.0000,0.8965,0.0000,0.000,2.4045,0.0000,0.000,0.0000,...,0.0000,0.8075,0.0000,0.0,0.0000,0.0000,-1.255598,1.077081e-04,7.161705e-04,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023,2023,MIR7515,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,2.000880,4.434787e-02,4.647932e-02,1.0
2024,2024,LOC101929989,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,32.7870,0.0,0.0000,0.0000,-1.143389,4.102652e-02,4.439796e-02,0.0
2025,2025,ACR.1,0.0000,0.0000,0.0000,0.228,0.0000,2.0852,0.000,4.7458,...,0.0000,0.0000,0.0000,0.0,2.5423,0.3553,-1.120220,1.215591e-02,2.073354e-02,0.0
2026,2026,SYT14.1,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,9.1070,0.0000,0.0,0.0000,0.0000,-1.124801,5.214655e-03,1.205852e-02,0.0
2027,2027,MIR3974,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,-2.416112,4.873712e-02,4.939475e-02,0.0

In [ ]:
DFM.to_csv('/content/drive/My Drive/Data_Set/DENV_gene/DEGs_set.csv')

In [ ]:
DFM

,Unnamed: 0,Gene,0,1,2,3,4,5,6,7,...,2238,2239,2240,2241,2242,2243,log2fc,p_value,adj_p_value,target
0,0,FGR,0.0000,0.0000,0.0000,0.000,2.9110,16.9374,0.000,1.2777,...,19.8922,18.1169,0.0000,0.0,0.0000,8.6683,2.312334,1.424200e-08,3.656048e-07,1.0
1,1,ENPP4,2.8671,11.4588,0.0000,0.000,13.4420,0.0000,0.000,617.6932,...,0.8117,0.0000,60.5167,0.0,0.0000,0.0000,1.055971,3.509842e-02,4.016773e-02,1.0
2,2,ST7,9.6391,44.6741,48.9423,50.224,45.3135,0.0000,87.121,0.7783,...,0.0000,9.3375,15.3363,0.0,4.3941,7.8650,-1.883971,1.298770e-05,1.371826e-04,0.0
3,3,OSBPL7,0.0000,0.3913,10.5258,0.000,6.4898,1.5395,0.000,0.0000,...,279.1432,6.5387,0.6939,0.0,2.4243,2.8046,-1.201447,3.824219e-04,1.882407e-03,0.0
4,4,CACNG3,0.0000,0.8965,0.0000,0.000,2.4045,0.0000,0.000,0.0000,...,0.0000,0.8075,0.0000,0.0,0.0000,0.0000,-1.255598,1.077081e-04,7.161705e-04,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023,2023,MIR7515,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,2.000880,4.434787e-02,4.647932e-02,1.0
2024,2024,LOC101929989,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,32.7870,0.0,0.0000,0.0000,-1.143389,4.102652e-02,4.439796e-02,0.0
2025,2025,ACR.1,0.0000,0.0000,0.0000,0.228,0.0000,2.0852,0.000,4.7458,...,0.0000,0.0000,0.0000,0.0,2.5423,0.3553,-1.120220,1.215591e-02,2.073354e-02,0.0
2026,2026,SYT14.1,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,9.1070,0.0000,0.0,0.0000,0.0000,-1.124801,5.214655e-03,1.205852e-02,0.0
2027,2027,MIR3974,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,...,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,-2.416112,4.873712e-02,4.939475e-02,0.0